SuperElf\ActiveConfig:
  exclusion_policy: ALL
  exclude: false
  access_type: public_property

  properties:
    createAndJoinStart:
        type: DateTimeImmutable<'Y-m-d\TH:i:s.u\Z'>
    createAndJoinEnd:
      type: DateTimeImmutable<'Y-m-d\TH:i:s.u\Z'>
    joinAndChoosePlayersStart:
      type: DateTimeImmutable<'Y-m-d\TH:i:s.u\Z'>
    joinAndChoosePlayersEnd:
      type: DateTimeImmutable<'Y-m-d\TH:i:s.u\Z'>
    sourceCompetitions:
      type: array<array>