SuperElf\CompetitionConfig:
  exclusion_policy: ALL
  exclude: false
  access_type: public_property

  properties:
    sourceCompetition:
      type: Sports\Competition
    points:
      type: SuperElf\Points
    createAndJoinPeriod:
      type: SuperElf\Period\View
    assemblePeriod:
      type: SuperElf\Period\Assemble
    transferPeriod:
      type: SuperElf\Period\Transfer